In [ ]:
import torch

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
lead_data = pd.read_csv("/content/Finaldataset44.csv")

# View the first 5 rows
lead_data.head()

,property_zip,longitude,latitude,township,township_name,nbhd,tract_geoid,tract_pop,tract_white_perc,commissioner_dist,...,Prior Tax Year Market Value Estimate (Land),Prior Tax Year Market Value Estimate (Building),Multi Property Indicator,Age,Use,Multi-Family Indicator,Near Major Road,Location Factor,Neigborhood Code (mapping),Town and Neighborhood
0,60614-4208,-87.653752,41.919176,74.0,North Chicago,12.0,1.703107e+10,4604.0,0.788010,12th,...,109360.0,632060.0,0.0,10.0,1.0,NaN,0.0,2.382927,12.0,7412.0
1,60655-3306,-87.710283,41.692759,72.0,Lake,422.0,1.703174e+10,4947.0,0.865171,11th,...,48010.0,157850.0,0.0,78.0,1.0,NaN,0.0,0.612438,422.0,72422.0
2,60625-6005,-87.721660,41.971745,71.0,Jefferson,81.0,1.703114e+10,4127.0,0.337533,12th,...,54370.0,234190.0,0.0,99.0,1.0,NaN,0.0,1.286040,81.0,7181.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,60630-1042,-87.780537,41.978346,71.0,Jefferson,430.0,1.703111e+10,5720.0,0.643881,12th,...,54750.0,216000.0,0.0,64.0,1.0,NaN,0.0,1.204453,430.0,71430.0

In [ ]:
lead_data7 = pd.read_csv("/content/matched_addresses.csv", on_bad_lines='skip')

<ipython-input-16-35df64c84e2e>:1: DtypeWarning: Columns (0,7,8,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  lead_data7 = pd.read_csv("/content/matched_addresses.csv", on_bad_lines='skip')

In [ ]:
lead_data7.tail()

,Private Service Line Material,Public Service Line Material,property_city,property_zip,mailing_address,mailing_state,latitude,longitude,township_name,school_elem_district,school_hs_district,address_x,address_y
541830,LEAD,SUSPECTED LEAD,CHICAGO,60630-3210,4704 N CENTRAL AVE,IL,41.966165,-87.767777,Jefferson,PRUSSING,TAFT HS,4704 N CENTRAL AVE,4704 N CENTRAL AVE
541831,NOT LEAD,SUSPECTED LEAD,CHICAGO,60638-5617,6318 S LONG AVE,IL,41.777551,-87.757196,Lake,GRIMES,KENNEDY HS,6318 S LONG AVE,6318 S LONG AVE
541832,NOT LEAD,NOT LEAD,CHICAGO,60611-3591,109 S ABERDEEN ST,IL,41.889888,-87.625831,North Chicago,OGDEN,WELLS HS,109 S ABERDEEN ST,405 N WABASH AVE
541833,NOT LEAD,NOT LEAD,CHICAGO,60611-3591,109 S ABERDEEN ST,IL,41.889829,-87.625685,North Chicago,OGDEN,WELLS HS,109 S ABERDEEN ST,405 N WABASH AVE
541834,NOT LEAD,NOT LEAD,CHICAGO,60632-1524,2502 W 55TH ST,IL,41.794082,-87.686728,Lake,CARSON,KELLY HS,2502 W 55TH ST,2502 W 55TH ST

In [ ]:
lead_data7 = lead_data7.drop(['address'], axis=1)

In [ ]:
merged_df = pd.merge(lead_data, lead_data7, on='property_zip', how='outer')

# Save merged dataframe to a new CSV file
merged_df.to_csv('merged_file.csv', index=False)

In [ ]:
merged_df.()

,property_zip,longitude_x,latitude_x,township,township_name_x,nbhd,tract_geoid,tract_pop,tract_white_perc,commissioner_dist,...,property_city,mailing_address,mailing_state,latitude_y,longitude_y,township_name_y,school_elem_district_y,school_hs_district,address_x,address_y
837720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SCHURZ HS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SCHURZ HS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Creating a neural

class Model(nn.Module):
  def __init__(self, in_features=11, h1=8, h2=9, out_features=4):
    super().__init__() #instantiate our nn.Module
    self.fc1 = nn.Linear(in_features, h1)#fully connected
    self.fc2 = nn.Linear(h1, h2)#moving through layers
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))#reclified linear unit(<0 make it 0, else use the value)
    x = F.relu(self.fc2(x))#reclified linear unit(<0 make it 0, else use the value)
    x = self.out(x)

    return x

In [ ]:
torch.manual_seed(41)
model=Model()

In [ ]:
dataset1.tail()

,Property Class,Neighborhood Code,Land Square Feet,Prior Tax Year Market Value Estimate (Land),Prior Tax Year Market Value Estimate (Building),Multi Property Indicator,Age,Use,Multi-Family Indicator,Near Major Road,Neigborhood Code (mapping),Private Service Line Material
368443,241,260,5314,21250,0,0,10,1,NaN,1.0,260,SUSPECTED LEAD
368444,241,260,5314,21250,0,0,10,1,NaN,1.0,260,SUSPECTED LEAD
368445,241,260,5314,21250,0,0,10,1,NaN,1.0,260,LEAD
368446,241,260,5314,21250,0,0,10,1,NaN,1.0,260,LEAD
368447,241,260,5314,21250,0,0,10,1,NaN,1.0,260,LEAD

In [ ]:
dataset1 = pd.read_csv("/content/merged_file_private.csv", on_bad_lines='skip')

In [ ]:
dataset1['Private Service Line Material'] = dataset1['Private Service Line Material'].replace('NOT LEAD', 0)
dataset1['Private Service Line Material'] = dataset1['Private Service Line Material'].replace('LEAD', 1)
dataset1['Private Service Line Material'] = dataset1['Private Service Line Material'].replace('SUSPECTED LEAD', 3)
dataset1['Private Service Line Material'] = dataset1['Private Service Line Material'].replace('GALVANIZED REQUIRING REPLACEMENT', 4)

NameError: name 'dataset1' is not defined

In [ ]:
X()

array([[2.9900e+02, 1.0000e+01, 1.8486e+04, ...,        nan, 0.0000e+00,
        1.0000e+01],
       [2.9900e+02, 1.0000e+01, 1.8486e+04, ...,        nan, 0.0000e+00,
        1.0000e+01],
       [2.9900e+02, 1.0000e+01, 1.8486e+04, ...,        nan, 0.0000e+00,
        1.0000e+01],
       ...,
       [2.4100e+02, 2.6000e+02, 5.3140e+03, ...,        nan, 1.0000e+00,
        2.6000e+02],
       [2.4100e+02, 2.6000e+02, 5.3140e+03, ...,        nan, 1.0000e+00,
        2.6000e+02],
       [2.4100e+02, 2.6000e+02, 5.3140e+03, ...,        nan, 1.0000e+00,
        2.6000e+02]])

In [ ]:
#Continuation of Neural Networking building:
X = dataset1.drop('Private Service Line Material', axis=1)
y = dataset1['Private Service Line Material']

In [ ]:
X = X.values
y=y.values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

NameError: name 'train_test_split' is not defined

In [ ]:
from sklearn.model_selection import train_test_split #lib

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)#Train Test split, 20% training

In [ ]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

In [ ]:
#NN building in progress, Some dataset cleansing was done via Excel